version: '1.0.{build}'

branches:
  only:
    - master

configuration:
  - Release

os: Visual Studio 2015

platform: Any CPU

environment:
  matrix:
    - VisualStudioVersion: 14.0
    - VisualStudioVersion: 12.0

init:
  - git config --global core.autocrlf true

before_build:
  - nuget restore %APPVEYOR_BUILD_FOLDER%\src\AutoMerge.sln

build:

test: off

artifacts:
  - path: '**\*.vsix'
