version: '1.0.{build}'

branches:
  only:
    - master

configuration:
  - Release

image: Visual Studio 2017

platform: Any CPU

environment:
  matrix:
    - VisualStudioVersion: 16.0
    - VisualStudioVersion: 15.0

init:
  - git config --global core.autocrlf true

build:

test: off

artifacts:
  - path: '**\*.vsix'
